language: node_js

addons:
  code_climate:
    repo_token: 7999d3c546e18743012d67dab3536c4dbbed672b52fd39410458126e76809d07

node_js:
  - "6"

script: npm run coverage

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
